Improvement: Add verbose mode to generated CLIs
palantir/conjure-go pull request #305
Opened 2022-05-04 20:32 UTC by asanderson15

## Before this PR

## After this PR

==COMMIT_MSG==
==COMMIT_MSG==

## Possible downsides?

2022-05-04 21:23 UTC, bmoylan requested changes
> Reviewed 8 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/palantir/conjure-go/305)* status: all files reviewed, 1 unresolved discussion (waiting on @asanderson15)

___
*[`conjure/cliwriter.go` line 122 at r2](https://reviewable.io/reviews/palantir/conjure-go/305#-N1Fwuyr9iLpKFFHpi-L:-N1Fwuyr9iLpKFFHpi-M:b6wc902) ([raw file](https://github.com/palantir/conjure-go/blob/43ffb42fb75619217293053cad6577e6f8873bf5/conjure/cliwriter.go#L122)):*
> ```Go
> 	file.List(jen.Id("verbose"), jen.Err()).Op(":=").Id("flags").Dot("GetBool").Call(jen.Lit(verboseFlagName))
> 	file.If(jen.Op("!").Id("verbose").Op("||").Err().Op("!=").Nil()).Block(
> 		jen.Return(jen.Id("ctx")))
> ```

instead should we initialize a noop/discard logger? Otherwise I think the default behavior will kick in and still print things


<!-- Sent from Reviewable.io -->

2022-05-05 19:22 UTC, asanderson15 reviewed
> *[Reviewable](https://reviewable.io/reviews/palantir/conjure-go/305)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @bmoylan)

___
*[`conjure/cliwriter.go` line 122 at r2](https://reviewable.io/reviews/palantir/conjure-go/305#-N1Fwuyr9iLpKFFHpi-L:-N1KezZ98PetPSD4BQLy:b-7q1dgo) ([raw file](https://github.com/palantir/conjure-go/blob/43ffb42fb75619217293053cad6577e6f8873bf5/conjure/cliwriter.go#L122)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

instead should we initialize a noop/discard logger? Otherwise I think the default behavior will kick in and still print things
</blockquote></details>

Yeah, good call. I forgot about the default impls. Updated.


<!-- Sent from Reviewable.io -->

2022-05-06 15:25 UTC, bmoylan approved these changes
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/palantir/conjure-go/305)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @asanderson15)



<!-- Sent from Reviewable.io -->

2022-05-06 15:27 UTC, merged

2022-05-06 15:27 UTC, svc-autorelease commented
Released [6.19.0](https://github.com/palantir/conjure-go/releases/tag/v6.19.0)