Fix: Fix typo in default generated CLI conf path
palantir/conjure-go pull request #312
Opened 2022-05-17 17:46 UTC by asanderson15

==COMMIT_MSG==
Fix typo in default generated CLI conf path
==COMMIT_MSG==

2022-05-17 17:53 UTC, tabboud approved these changes

2022-05-17 17:58 UTC, tabboud requested changes
Looks like files need to be re-generated

2022-05-18 17:19 UTC, asanderson15 commented
@tabboud updated

2022-05-18 21:55 UTC, tabboud approved these changes

2022-05-18 21:55 UTC, merged