Use WithRawRequestBodyProvider for binary client requests
palantir/conjure-go pull request #43
Opened 2019-04-03 01:29 UTC by johnhferland

Use `WithRawRequestBodyProvider` instead of `WithRawRequestBody` so retries will have the body set.

Note:  Formerly the generated server code used the service interface, but now they each have their own interfaces. The interface used by the server hasn't changed at all, but the binary case for the service has been modified.

Fixes: https://github.com/palantir/conjure-go/issues/41

2019-04-03 03:23 UTC, bmoylan requested changes
> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/conjure-go/43)* status: all files reviewed, 3 unresolved discussions (waiting on @johnhferland)

___
*[conjure/serverwriter.go, line 229 at r1](https://reviewable.io/reviews/palantir/conjure-go/43#-LbWCtpl9JLAUkKh_Ti4:-LbWCtpl9JLAUkKh_Ti5:bmf3fvo) ([raw file](https://github.com/palantir/conjure-go/blob/1374ba39bf80c31cfb68e5b7708d0ecbeefa01b0/conjure/serverwriter.go#L229)):*
> ```Go
> 		return nil, err
> 	}
> 	if hasHeaderAuth || hasCookieAuth {
> ```

Let's not create the WithAuth interfaces server-side since they aren't accepted by the handlers.
___
*[conjure/types/types.go, line 279 at r1](https://reviewable.io/reviews/palantir/conjure-go/43#-LbWBGiw2gA5dhvqGlFr:-LbWBGiw2gA5dhvqGlFs:bvabj61) ([raw file](https://github.com/palantir/conjure-go/blob/1374ba39bf80c31cfb68e5b7708d0ecbeefa01b0/conjure/types/types.go#L279)):*
> ```Go
> }
> 
> type funcType struct {
> ```

can we add some tests for this type?
___
*[conjure/types/types.go, line 287 at r1](https://reviewable.io/reviews/palantir/conjure-go/43#-LbWBBcQ1tmN9d9kTKqv:-LbWBBcQ1tmN9d9kTKqw:b-lb515w) ([raw file](https://github.com/palantir/conjure-go/blob/1374ba39bf80c31cfb68e5b7708d0ecbeefa01b0/conjure/types/types.go#L287)):*
> ```Go
> 	inputs := goTypes(f.inputs, info)
> 	outputs := goTypes(f.outputs, info)
> 	return fmt.Sprintf("func(%s) %s", strings.Join(inputs, ", "), strings.Join(outputs, ", "))
> ```

if there are multiple outputs they need to be wrapped in parentheses


<!-- Sent from Reviewable.io -->

2019-04-05 03:15 UTC, johnhferland reviewed
> *[Reviewable](https://reviewable.io/reviews/palantir/conjure-go/43)* status: 20 of 26 files reviewed, 3 unresolved discussions (waiting on @bmoylan)

___
*[conjure/serverwriter.go, line 229 at r1](https://reviewable.io/reviews/palantir/conjure-go/43#-LbWCtpl9JLAUkKh_Ti4:-LbfMu467l6RS1Sb9hfr:b-896fix) ([raw file](https://github.com/palantir/conjure-go/blob/1374ba39bf80c31cfb68e5b7708d0ecbeefa01b0/conjure/serverwriter.go#L229)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

Let's not create the WithAuth interfaces server-side since they aren't accepted by the handlers.
</blockquote></details>

Done.
___
*[conjure/types/types.go, line 279 at r1](https://reviewable.io/reviews/palantir/conjure-go/43#-LbWBGiw2gA5dhvqGlFr:-LbfU8Zc1kZUPbS-nggL:b34r7cn) ([raw file](https://github.com/palantir/conjure-go/blob/1374ba39bf80c31cfb68e5b7708d0ecbeefa01b0/conjure/types/types.go#L279)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

can we add some tests for this type?
</blockquote></details>

Added a test! I alseo made the funcType have Typer inputs and outputs because that seemed more correct.
___
*[conjure/types/types.go, line 287 at r1](https://reviewable.io/reviews/palantir/conjure-go/43#-LbWBBcQ1tmN9d9kTKqv:-LbfUMjNCXZi1BhbxEw5:b5wu4x6) ([raw file](https://github.com/palantir/conjure-go/blob/1374ba39bf80c31cfb68e5b7708d0ecbeefa01b0/conjure/types/types.go#L287)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

if there are multiple outputs they need to be wrapped in parentheses
</blockquote></details>

Handled the edge case. It looks like always returning parentheses was valid, but I thought it looked much nicer not to do so.


<!-- Sent from Reviewable.io -->

2019-04-05 06:56 UTC, bmoylan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thanks! good to merge?

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palantir/conjure-go/43#-:-LbgH81k9byF_zmkkXr5:b-yjjm9s)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-04-05 14:40 UTC, johnhferland commented
Yeah, let's merge and tag a major version bump.

2019-04-05 16:25 UTC, merged